services:
  opencourseapi:
<<<<<<< HEAD
    ports:
      - "5000:5000"
    image: opencourse.azurecr.io/opencourseapi:latest
=======
    image: opencourse.azurecr.io/opencourseapi:latest
    environment:
      MONGODB_HOST: mongodb://mongo
      MONGODB_USER: root
      MONGODB_PASS: rootpassword
    ports:
      - 5000:5000
    depends_on:
      - mongo
>>>>>>> bc58682 (allow api to connect to database)
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: rootpassword
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev
<<<<<<< HEAD
    depends_on:
      - mongo
    ports:
      - "8888:8081"
=======
    ports:
      - 8888:8081
    depends_on:
      - mongo
>>>>>>> bc58682 (allow api to connect to database)

volumes:
  mongodb_data_container:
      
